# Нет ошибки, потому что в конфиге flake8 игнорируются ошибки F401 В __init__.py
from .main import sumTwoInt
